1. 自定义层。

构造一个没有任何参数的自定义层

In [3]:
import torch
import torch.nn.functional as F
from torch import nn

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

2. 将层作为组件合并到构建更复杂的模型中

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-9.3132e-10, grad_fn=<MeanBackward0>)

3. 带参数的层

torch.randn(in_units, units) - 输入大小 X 输出大小 的一个随机矩阵

nn.Parameter(torch.randn(in_units, units))  加入梯度



In [11]:
class MyLinear(nn.Module):
    
    # 输入维度， 输出维度
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
        
    def forward(self, X):
        Linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(Linear)

dense = MyLinear(5, 3)
dense.weight

Parameter containing:
tensor([[ 1.0269,  1.7453, -0.8525],
        [ 0.4315, -0.2286,  0.1855],
        [ 0.3719, -1.1206,  1.0271],
        [-0.5066,  0.7209,  1.0432],
        [-0.5338, -1.2791, -0.6887]], requires_grad=True)

4.使用自定义层直接执行正向传播计算

In [12]:
dense(torch.rand(2, 5))

tensor([[0.3832, 0.1827, 0.0000],
        [0.0000, 0.8000, 0.0000]])

In [13]:
# 使用自定义层 构建模型
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[12.5125],
        [13.2256]])